# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hckctl < Formula
  desc "The declarative HaCKing Tool"
  homepage "https://github.com/hckops/hckctl"
  version "0.12.5"

  depends_on "docker" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.5/hckctl-0.12.5-darwin-x86_64.tar.gz"
      sha256 "aced99ed71acea9624f917eff5897f138e8609a1636ef4b87a499376fcf8e57b"

      def install
        bin.install "hckctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.5/hckctl-0.12.5-darwin-arm64.tar.gz"
      sha256 "a9b1de188ab6dd8b2d4100a7f1651453591e5c1c217a3b05dd209ef7f8c92d73"

      def install
        bin.install "hckctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.5/hckctl-0.12.5-linux-x86_64.tar.gz"
      sha256 "cdd0a8ac6f102341a65893f92ad308d230601213f70d37cc6556923ab054b4d4"

      def install
        bin.install "hckctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.5/hckctl-0.12.5-linux-arm64.tar.gz"
      sha256 "545dd150b783d1e61557c801b92e331cf455801dc3d62803c42e4cc9384742df"

      def install
        bin.install "hckctl"
      end
    end
  end

  test do
    hckctl version
  end
end
