# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hckctl < Formula
  desc "The declarative HaCKing Tool"
  homepage "https://github.com/hckops/hckctl"
  version "0.12.7"

  depends_on "docker" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.7/hckctl-0.12.7-darwin-x86_64.tar.gz"
      sha256 "b4611d01ecd23eb87299aa5bdc1f51eabbbdab3fe797debbd8880fa278310117"

      def install
        bin.install "hckctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.7/hckctl-0.12.7-darwin-arm64.tar.gz"
      sha256 "d11df799b6060493e4359b38ae3311db5f4fcaf708c0d734197c89dfd7f03e1b"

      def install
        bin.install "hckctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.7/hckctl-0.12.7-linux-arm64.tar.gz"
      sha256 "8cfdc6ec95b8d2557fc24df85564f7abaf94781ad551f315a1ec909598e8f70a"

      def install
        bin.install "hckctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hckops/hckctl/releases/download/v0.12.7/hckctl-0.12.7-linux-x86_64.tar.gz"
      sha256 "48dea16faf8986da3d68eb20a25850bc168f4a33b40c4e623ae977b605c6722f"

      def install
        bin.install "hckctl"
      end
    end
  end

  test do
    hckctl version
  end
end
